# Generated by Django 4.2 on 2025-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='math_problems/')),
                ('extracted_equation', models.TextField()),
                ('solution', models.TextField()),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
