# Generated by Django 4.2 on 2025-05-24 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathproblem',
            old_name='input_text',
            new_name='extracted_problem',
        ),
        migrations.RemoveField(
            model_name='mathproblem',
            name='extracted_equation',
        ),
        migrations.RemoveField(
            model_name='mathproblem',
            name='input_image',
        ),
        migrations.AddField(
            model_name='mathproblem',
            name='input_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('PDF', 'PDF')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathproblem',
            name='original_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mathproblem',
            name='processing_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mathproblem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
